name: Build and deploy
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t renj4h/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: push
        run: docker push renj4h/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB}}
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: render config
        run: |
          mkdir deploy_folder
          cat docker-compose-ci.yaml | envsubst > deploy_folder/docker-compose.yaml
          cat .env | envsubst > deploy_folder/.env
      - name: check copy files
        run: |
          ls deploy_folder
      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "deploy_folder/*"
          target: "todolist"
          strip_components: 1
      - name: run docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd todolist
            echo ${{ secrets.SERVER_PASSWORD }} | sudo -S docker-compose down
            echo ${{ secrets.SERVER_PASSWORD }} | sudo -S docker-compose up -d